version: 2

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build HTMLZIP, PDF & ePub
formats:
  - htmlzip
  - epub
  - pdf
